package game.events;

public enum EventType {
    NO_EVENT,
    APP_UPDATE_EVENT,
    APP_TICK_EVENT,
    APP_RENDER_EVENT,
    WINDOW_CLOSED_EVENT,
    WINDOW_RESIZED_EVENT,
    WINDOW_MOVED_EVENT,
    KEY_PRESSED_EVENT,
    KEY_RELEASED_EVENT,
    KEY_REPEATED_EVENT,
    MOUSE_PRESSED_EVENT,
    MOUSE_RELEASED_EVENT,
    MOUSE_MOVED_EVENT,
    MOUSE_SCROLLED_EVENT,
    ENTITY_CREATED_EVENT,
    ENTITY_UPDATED_EVENT,
    ENTITY_DESTROYED_EVENT,
}
